-- 미확인 음식 제보 큐 (ADM-002)
CREATE TABLE unidentified_food_reports (
                                           id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           registration_id BIGINT,                       -- 느슨한 참조, nullable
                                           description     VARCHAR(200) NOT NULL,
                                           reject_reason   VARCHAR(200),                 -- 반려 시에만 채워짐
                                           status          VARCHAR(20)  NOT NULL,        -- PENDING / ACCEPTED / REJECTED
                                           created_at      TIMESTAMP    NOT NULL,
                                           updated_at      TIMESTAMP    NOT NULL
);

-- 대기 목록을 상태로 자주 조회하므로 인덱스
CREATE INDEX idx_unidentified_food_reports_status ON unidentified_food_reports (status);

-- 음식 등록 승인 큐 (AI가 못 끝낸 등록 → 관리자 처리)
CREATE TABLE food_registration_requests (
                                            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            registration_id BIGINT,
                                            description     VARCHAR(200) NOT NULL,
                                            failure_reason  VARCHAR(200),                 -- AI가 왜 못 끝냈는지
                                            reject_reason   VARCHAR(200),
                                            status          VARCHAR(20)  NOT NULL,        -- PENDING / COMPLETED / REJECTED
                                            created_at      TIMESTAMP    NOT NULL,
                                            updated_at      TIMESTAMP    NOT NULL
);

CREATE INDEX idx_food_registration_requests_status ON food_registration_requests (status);